###
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2024 Tenstorrent Inc.
###

name: Build Application

on:
    push:
        branches:
            - main
            - dev # temporarily for testing
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: macos-13-arm64
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run build and package
              run: npm run package

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: packaged-app
                  path: release/build/*.dmg # Updated path to where your build outputs the .dmg files
