###
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2024 Tenstorrent Inc.
###
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build MacOS Application

on:
    push:
        branches: [ "main", "dev" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm install

            - run: npm run package

            - uses: actions/upload-artifact@v3
              with:
                  name: packaged-app
                  path: release/build/*.dmg

